module.exports = {
    mainCssUrl:     '/includes/css/warnerburg.css',
    homeDark:       '/images/navigation/homedarks.png',
    homeLight:      '/images/navigation/homelights.png',
    galleryDark:    '/images/navigation/gallerydarks.png',
    galleryLight:   '/images/navigation/gallerylights.png',
    comicDark:      '/images/navigation/comicdarks.png',
    comicLight:     '/images/navigation/comiclights.png',
    storeDark:      '/images/navigation/storedarks.png',
    storeLight:     '/images/navigation/storelights.png',
    infoDark:       '/images/navigation/infodarks.png',
    infoLight:      '/images/navigation/infolights.png',
    linksDark:      '/images/navigation/linksdarks.png',
    linksLight:     '/images/navigation/linkslights.png',
    homeUrl:        '/',
    galleryUrl:     '/gallery',
    storeUrl:       '/store',
    comicUrl:       '/comic',
    archivesUrl:    '/comic/archives',
    infoUrl:        '/info'
};